// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHzRH66IySPgxL711n6CEKw633DKuZAsk',
    appId: '1:359862813046:web:68678a22660a509f9dba57',
    messagingSenderId: '359862813046',
    projectId: 'mcl-project-b7af6',
    authDomain: 'mcl-project-b7af6.firebaseapp.com',
    storageBucket: 'mcl-project-b7af6.appspot.com',
    measurementId: 'G-T2DSXLQNYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS24szOd82bLF0n91HYapuNLnlqk8R324',
    appId: '1:359862813046:android:0fd0a38b7b80d0859dba57',
    messagingSenderId: '359862813046',
    projectId: 'mcl-project-b7af6',
    storageBucket: 'mcl-project-b7af6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcO19_ew4tmZrqUyAO1hbOGw7dxMARlpI',
    appId: '1:359862813046:ios:df6786a9979249cc9dba57',
    messagingSenderId: '359862813046',
    projectId: 'mcl-project-b7af6',
    storageBucket: 'mcl-project-b7af6.appspot.com',
    iosClientId: '359862813046-0hbnq3vvb21gj9ri43sumi5vjsvsm2vq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mclAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcO19_ew4tmZrqUyAO1hbOGw7dxMARlpI',
    appId: '1:359862813046:ios:df6786a9979249cc9dba57',
    messagingSenderId: '359862813046',
    projectId: 'mcl-project-b7af6',
    storageBucket: 'mcl-project-b7af6.appspot.com',
    iosClientId: '359862813046-0hbnq3vvb21gj9ri43sumi5vjsvsm2vq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mclAdmin',
  );
}
